export const DATE_RANGE_BOOKING_REQUEST = "DATE_RANGE_BOOKING_REQUEST";
export const DATE_RANGE_BOOKING_SUCCESS = "DATE_RANGE_BOOKING_SUCCESS";
export const DATE_RANGE_BOOKING_FAIL = "DATE_RANGE_BOOKING_FAIL";
