export const CREATE_OWNERSHIP_REQUEST = "CREATE_OWNERSHIP_REQUEST";
export const CREATE_OWNERSHIP_SUCCESS = "CREATE_OWNERSHIP_SUCCESS";
export const CREATE_OWNERSHIP_FAIL = "CREATE_OWNERSHIP_FAIL";
export const CREATE_OWNERSHIP_RESET = "CREATE_OWNERSHIP_RESET";
